# CMake generated Testfile for 
# Source directory: /home/sjtuwhl/ROBOTLAB_WS/src/ros_control-melodic-devel/joint_limits_interface
# Build directory: /home/sjtuwhl/ROBOTLAB_WS/devel/ros_control-melodic-devel/joint_limits_interface
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(_ctest_joint_limits_interface_gtest_joint_limits_interface_test "/home/sjtuwhl/ROBOTLAB_WS/devel/catkin_generated/env_cached.sh" "/usr/bin/python2" "/opt/ros/melodic/share/catkin/cmake/test/run_tests.py" "/home/sjtuwhl/ROBOTLAB_WS/devel/test_results/joint_limits_interface/gtest-joint_limits_interface_test.xml" "--return-code" "/home/sjtuwhl/ROBOTLAB_WS/devel/lib/joint_limits_interface/joint_limits_interface_test --gtest_output=xml:/home/sjtuwhl/ROBOTLAB_WS/devel/test_results/joint_limits_interface/gtest-joint_limits_interface_test.xml")
set_tests_properties(_ctest_joint_limits_interface_gtest_joint_limits_interface_test PROPERTIES  _BACKTRACE_TRIPLES "/opt/ros/melodic/share/catkin/cmake/test/tests.cmake;143;add_test;/opt/ros/melodic/share/catkin/cmake/test/gtest.cmake;89;catkin_run_tests_target;/opt/ros/melodic/share/catkin/cmake/test/gtest.cmake;28;_catkin_add_google_test;/home/sjtuwhl/ROBOTLAB_WS/src/ros_control-melodic-devel/joint_limits_interface/CMakeLists.txt;32;catkin_add_gtest;/home/sjtuwhl/ROBOTLAB_WS/src/ros_control-melodic-devel/joint_limits_interface/CMakeLists.txt;0;")
add_test(_ctest_joint_limits_interface_gtest_joint_limits_urdf_test "/home/sjtuwhl/ROBOTLAB_WS/devel/catkin_generated/env_cached.sh" "/usr/bin/python2" "/opt/ros/melodic/share/catkin/cmake/test/run_tests.py" "/home/sjtuwhl/ROBOTLAB_WS/devel/test_results/joint_limits_interface/gtest-joint_limits_urdf_test.xml" "--return-code" "/home/sjtuwhl/ROBOTLAB_WS/devel/lib/joint_limits_interface/joint_limits_urdf_test --gtest_output=xml:/home/sjtuwhl/ROBOTLAB_WS/devel/test_results/joint_limits_interface/gtest-joint_limits_urdf_test.xml")
set_tests_properties(_ctest_joint_limits_interface_gtest_joint_limits_urdf_test PROPERTIES  _BACKTRACE_TRIPLES "/opt/ros/melodic/share/catkin/cmake/test/tests.cmake;143;add_test;/opt/ros/melodic/share/catkin/cmake/test/gtest.cmake;89;catkin_run_tests_target;/opt/ros/melodic/share/catkin/cmake/test/gtest.cmake;28;_catkin_add_google_test;/home/sjtuwhl/ROBOTLAB_WS/src/ros_control-melodic-devel/joint_limits_interface/CMakeLists.txt;38;catkin_add_gtest;/home/sjtuwhl/ROBOTLAB_WS/src/ros_control-melodic-devel/joint_limits_interface/CMakeLists.txt;0;")
add_test(_ctest_joint_limits_interface_rostest_test_joint_limits_rosparam.test "/home/sjtuwhl/ROBOTLAB_WS/devel/catkin_generated/env_cached.sh" "/usr/bin/python2" "/opt/ros/melodic/share/catkin/cmake/test/run_tests.py" "/home/sjtuwhl/ROBOTLAB_WS/devel/test_results/joint_limits_interface/rostest-test_joint_limits_rosparam.xml" "--return-code" "/opt/ros/melodic/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/sjtuwhl/ROBOTLAB_WS/src/ros_control-melodic-devel/joint_limits_interface --package=joint_limits_interface --results-filename test_joint_limits_rosparam.xml --results-base-dir \"/home/sjtuwhl/ROBOTLAB_WS/devel/test_results\" /home/sjtuwhl/ROBOTLAB_WS/src/ros_control-melodic-devel/joint_limits_interface/test/joint_limits_rosparam.test ")
set_tests_properties(_ctest_joint_limits_interface_rostest_test_joint_limits_rosparam.test PROPERTIES  _BACKTRACE_TRIPLES "/opt/ros/melodic/share/catkin/cmake/test/tests.cmake;143;add_test;/opt/ros/melodic/share/rostest/cmake/rostest-extras.cmake;52;catkin_run_tests_target;/opt/ros/melodic/share/rostest/cmake/rostest-extras.cmake;80;add_rostest;/opt/ros/melodic/share/rostest/cmake/rostest-extras.cmake;100;_add_rostest_google_test;/home/sjtuwhl/ROBOTLAB_WS/src/ros_control-melodic-devel/joint_limits_interface/CMakeLists.txt;44;add_rostest_gtest;/home/sjtuwhl/ROBOTLAB_WS/src/ros_control-melodic-devel/joint_limits_interface/CMakeLists.txt;0;")
