# CMake generated Testfile for 
# Source directory: /home/sjtuwhl/ROBOTLAB_WS/src/ros_control-melodic-devel/transmission_interface
# Build directory: /home/sjtuwhl/ROBOTLAB_WS/devel/ros_control-melodic-devel/transmission_interface
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(_ctest_transmission_interface_gtest_simple_transmission_test "/home/sjtuwhl/ROBOTLAB_WS/devel/catkin_generated/env_cached.sh" "/usr/bin/python2" "/opt/ros/melodic/share/catkin/cmake/test/run_tests.py" "/home/sjtuwhl/ROBOTLAB_WS/devel/test_results/transmission_interface/gtest-simple_transmission_test.xml" "--return-code" "/home/sjtuwhl/ROBOTLAB_WS/devel/lib/transmission_interface/simple_transmission_test --gtest_output=xml:/home/sjtuwhl/ROBOTLAB_WS/devel/test_results/transmission_interface/gtest-simple_transmission_test.xml")
set_tests_properties(_ctest_transmission_interface_gtest_simple_transmission_test PROPERTIES  _BACKTRACE_TRIPLES "/opt/ros/melodic/share/catkin/cmake/test/tests.cmake;143;add_test;/opt/ros/melodic/share/catkin/cmake/test/gtest.cmake;89;catkin_run_tests_target;/opt/ros/melodic/share/catkin/cmake/test/gtest.cmake;28;_catkin_add_google_test;/home/sjtuwhl/ROBOTLAB_WS/src/ros_control-melodic-devel/transmission_interface/CMakeLists.txt;97;catkin_add_gtest;/home/sjtuwhl/ROBOTLAB_WS/src/ros_control-melodic-devel/transmission_interface/CMakeLists.txt;0;")
add_test(_ctest_transmission_interface_gtest_differential_transmission_test "/home/sjtuwhl/ROBOTLAB_WS/devel/catkin_generated/env_cached.sh" "/usr/bin/python2" "/opt/ros/melodic/share/catkin/cmake/test/run_tests.py" "/home/sjtuwhl/ROBOTLAB_WS/devel/test_results/transmission_interface/gtest-differential_transmission_test.xml" "--return-code" "/home/sjtuwhl/ROBOTLAB_WS/devel/lib/transmission_interface/differential_transmission_test --gtest_output=xml:/home/sjtuwhl/ROBOTLAB_WS/devel/test_results/transmission_interface/gtest-differential_transmission_test.xml")
set_tests_properties(_ctest_transmission_interface_gtest_differential_transmission_test PROPERTIES  _BACKTRACE_TRIPLES "/opt/ros/melodic/share/catkin/cmake/test/tests.cmake;143;add_test;/opt/ros/melodic/share/catkin/cmake/test/gtest.cmake;89;catkin_run_tests_target;/opt/ros/melodic/share/catkin/cmake/test/gtest.cmake;28;_catkin_add_google_test;/home/sjtuwhl/ROBOTLAB_WS/src/ros_control-melodic-devel/transmission_interface/CMakeLists.txt;100;catkin_add_gtest;/home/sjtuwhl/ROBOTLAB_WS/src/ros_control-melodic-devel/transmission_interface/CMakeLists.txt;0;")
add_test(_ctest_transmission_interface_gtest_four_bar_linkage_transmission_test "/home/sjtuwhl/ROBOTLAB_WS/devel/catkin_generated/env_cached.sh" "/usr/bin/python2" "/opt/ros/melodic/share/catkin/cmake/test/run_tests.py" "/home/sjtuwhl/ROBOTLAB_WS/devel/test_results/transmission_interface/gtest-four_bar_linkage_transmission_test.xml" "--return-code" "/home/sjtuwhl/ROBOTLAB_WS/devel/lib/transmission_interface/four_bar_linkage_transmission_test --gtest_output=xml:/home/sjtuwhl/ROBOTLAB_WS/devel/test_results/transmission_interface/gtest-four_bar_linkage_transmission_test.xml")
set_tests_properties(_ctest_transmission_interface_gtest_four_bar_linkage_transmission_test PROPERTIES  _BACKTRACE_TRIPLES "/opt/ros/melodic/share/catkin/cmake/test/tests.cmake;143;add_test;/opt/ros/melodic/share/catkin/cmake/test/gtest.cmake;89;catkin_run_tests_target;/opt/ros/melodic/share/catkin/cmake/test/gtest.cmake;28;_catkin_add_google_test;/home/sjtuwhl/ROBOTLAB_WS/src/ros_control-melodic-devel/transmission_interface/CMakeLists.txt;103;catkin_add_gtest;/home/sjtuwhl/ROBOTLAB_WS/src/ros_control-melodic-devel/transmission_interface/CMakeLists.txt;0;")
add_test(_ctest_transmission_interface_gtest_transmission_interface_test "/home/sjtuwhl/ROBOTLAB_WS/devel/catkin_generated/env_cached.sh" "/usr/bin/python2" "/opt/ros/melodic/share/catkin/cmake/test/run_tests.py" "/home/sjtuwhl/ROBOTLAB_WS/devel/test_results/transmission_interface/gtest-transmission_interface_test.xml" "--return-code" "/home/sjtuwhl/ROBOTLAB_WS/devel/lib/transmission_interface/transmission_interface_test --gtest_output=xml:/home/sjtuwhl/ROBOTLAB_WS/devel/test_results/transmission_interface/gtest-transmission_interface_test.xml")
set_tests_properties(_ctest_transmission_interface_gtest_transmission_interface_test PROPERTIES  _BACKTRACE_TRIPLES "/opt/ros/melodic/share/catkin/cmake/test/tests.cmake;143;add_test;/opt/ros/melodic/share/catkin/cmake/test/gtest.cmake;89;catkin_run_tests_target;/opt/ros/melodic/share/catkin/cmake/test/gtest.cmake;28;_catkin_add_google_test;/home/sjtuwhl/ROBOTLAB_WS/src/ros_control-melodic-devel/transmission_interface/CMakeLists.txt;106;catkin_add_gtest;/home/sjtuwhl/ROBOTLAB_WS/src/ros_control-melodic-devel/transmission_interface/CMakeLists.txt;0;")
add_test(_ctest_transmission_interface_gtest_transmission_parser_test "/home/sjtuwhl/ROBOTLAB_WS/devel/catkin_generated/env_cached.sh" "/usr/bin/python2" "/opt/ros/melodic/share/catkin/cmake/test/run_tests.py" "/home/sjtuwhl/ROBOTLAB_WS/devel/test_results/transmission_interface/gtest-transmission_parser_test.xml" "--return-code" "/home/sjtuwhl/ROBOTLAB_WS/devel/lib/transmission_interface/transmission_parser_test --gtest_output=xml:/home/sjtuwhl/ROBOTLAB_WS/devel/test_results/transmission_interface/gtest-transmission_parser_test.xml")
set_tests_properties(_ctest_transmission_interface_gtest_transmission_parser_test PROPERTIES  _BACKTRACE_TRIPLES "/opt/ros/melodic/share/catkin/cmake/test/tests.cmake;143;add_test;/opt/ros/melodic/share/catkin/cmake/test/gtest.cmake;89;catkin_run_tests_target;/opt/ros/melodic/share/catkin/cmake/test/gtest.cmake;28;_catkin_add_google_test;/home/sjtuwhl/ROBOTLAB_WS/src/ros_control-melodic-devel/transmission_interface/CMakeLists.txt;109;catkin_add_gtest;/home/sjtuwhl/ROBOTLAB_WS/src/ros_control-melodic-devel/transmission_interface/CMakeLists.txt;0;")
add_test(_ctest_transmission_interface_gtest_simple_transmission_loader_test "/home/sjtuwhl/ROBOTLAB_WS/devel/catkin_generated/env_cached.sh" "/usr/bin/python2" "/opt/ros/melodic/share/catkin/cmake/test/run_tests.py" "/home/sjtuwhl/ROBOTLAB_WS/devel/test_results/transmission_interface/gtest-simple_transmission_loader_test.xml" "--return-code" "/home/sjtuwhl/ROBOTLAB_WS/devel/lib/transmission_interface/simple_transmission_loader_test --gtest_output=xml:/home/sjtuwhl/ROBOTLAB_WS/devel/test_results/transmission_interface/gtest-simple_transmission_loader_test.xml")
set_tests_properties(_ctest_transmission_interface_gtest_simple_transmission_loader_test PROPERTIES  _BACKTRACE_TRIPLES "/opt/ros/melodic/share/catkin/cmake/test/tests.cmake;143;add_test;/opt/ros/melodic/share/catkin/cmake/test/gtest.cmake;89;catkin_run_tests_target;/opt/ros/melodic/share/catkin/cmake/test/gtest.cmake;28;_catkin_add_google_test;/home/sjtuwhl/ROBOTLAB_WS/src/ros_control-melodic-devel/transmission_interface/CMakeLists.txt;112;catkin_add_gtest;/home/sjtuwhl/ROBOTLAB_WS/src/ros_control-melodic-devel/transmission_interface/CMakeLists.txt;0;")
add_test(_ctest_transmission_interface_gtest_differential_transmission_loader_test "/home/sjtuwhl/ROBOTLAB_WS/devel/catkin_generated/env_cached.sh" "/usr/bin/python2" "/opt/ros/melodic/share/catkin/cmake/test/run_tests.py" "/home/sjtuwhl/ROBOTLAB_WS/devel/test_results/transmission_interface/gtest-differential_transmission_loader_test.xml" "--return-code" "/home/sjtuwhl/ROBOTLAB_WS/devel/lib/transmission_interface/differential_transmission_loader_test --gtest_output=xml:/home/sjtuwhl/ROBOTLAB_WS/devel/test_results/transmission_interface/gtest-differential_transmission_loader_test.xml")
set_tests_properties(_ctest_transmission_interface_gtest_differential_transmission_loader_test PROPERTIES  _BACKTRACE_TRIPLES "/opt/ros/melodic/share/catkin/cmake/test/tests.cmake;143;add_test;/opt/ros/melodic/share/catkin/cmake/test/gtest.cmake;89;catkin_run_tests_target;/opt/ros/melodic/share/catkin/cmake/test/gtest.cmake;28;_catkin_add_google_test;/home/sjtuwhl/ROBOTLAB_WS/src/ros_control-melodic-devel/transmission_interface/CMakeLists.txt;115;catkin_add_gtest;/home/sjtuwhl/ROBOTLAB_WS/src/ros_control-melodic-devel/transmission_interface/CMakeLists.txt;0;")
add_test(_ctest_transmission_interface_gtest_four_bar_linkage_transmission_loader_test "/home/sjtuwhl/ROBOTLAB_WS/devel/catkin_generated/env_cached.sh" "/usr/bin/python2" "/opt/ros/melodic/share/catkin/cmake/test/run_tests.py" "/home/sjtuwhl/ROBOTLAB_WS/devel/test_results/transmission_interface/gtest-four_bar_linkage_transmission_loader_test.xml" "--return-code" "/home/sjtuwhl/ROBOTLAB_WS/devel/lib/transmission_interface/four_bar_linkage_transmission_loader_test --gtest_output=xml:/home/sjtuwhl/ROBOTLAB_WS/devel/test_results/transmission_interface/gtest-four_bar_linkage_transmission_loader_test.xml")
set_tests_properties(_ctest_transmission_interface_gtest_four_bar_linkage_transmission_loader_test PROPERTIES  _BACKTRACE_TRIPLES "/opt/ros/melodic/share/catkin/cmake/test/tests.cmake;143;add_test;/opt/ros/melodic/share/catkin/cmake/test/gtest.cmake;89;catkin_run_tests_target;/opt/ros/melodic/share/catkin/cmake/test/gtest.cmake;28;_catkin_add_google_test;/home/sjtuwhl/ROBOTLAB_WS/src/ros_control-melodic-devel/transmission_interface/CMakeLists.txt;118;catkin_add_gtest;/home/sjtuwhl/ROBOTLAB_WS/src/ros_control-melodic-devel/transmission_interface/CMakeLists.txt;0;")
add_test(_ctest_transmission_interface_gtest_transmission_interface_loader_test "/home/sjtuwhl/ROBOTLAB_WS/devel/catkin_generated/env_cached.sh" "/usr/bin/python2" "/opt/ros/melodic/share/catkin/cmake/test/run_tests.py" "/home/sjtuwhl/ROBOTLAB_WS/devel/test_results/transmission_interface/gtest-transmission_interface_loader_test.xml" "--return-code" "/home/sjtuwhl/ROBOTLAB_WS/devel/lib/transmission_interface/transmission_interface_loader_test --gtest_output=xml:/home/sjtuwhl/ROBOTLAB_WS/devel/test_results/transmission_interface/gtest-transmission_interface_loader_test.xml")
set_tests_properties(_ctest_transmission_interface_gtest_transmission_interface_loader_test PROPERTIES  _BACKTRACE_TRIPLES "/opt/ros/melodic/share/catkin/cmake/test/tests.cmake;143;add_test;/opt/ros/melodic/share/catkin/cmake/test/gtest.cmake;89;catkin_run_tests_target;/opt/ros/melodic/share/catkin/cmake/test/gtest.cmake;28;_catkin_add_google_test;/home/sjtuwhl/ROBOTLAB_WS/src/ros_control-melodic-devel/transmission_interface/CMakeLists.txt;121;catkin_add_gtest;/home/sjtuwhl/ROBOTLAB_WS/src/ros_control-melodic-devel/transmission_interface/CMakeLists.txt;0;")
