# CMake generated Testfile for 
# Source directory: /home/sjtuwhl/ROBOTLAB_WS/src/gazebo_ros_pkgs-melodic-devel/gazebo_ros/test
# Build directory: /home/sjtuwhl/ROBOTLAB_WS/devel/gazebo_ros_pkgs-melodic-devel/gazebo_ros/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(_ctest_gazebo_ros_rostest_test_ros_network_ros_network_default.test "/home/sjtuwhl/ROBOTLAB_WS/devel/catkin_generated/env_cached.sh" "/usr/bin/python2" "/opt/ros/melodic/share/catkin/cmake/test/run_tests.py" "/home/sjtuwhl/ROBOTLAB_WS/devel/test_results/gazebo_ros/rostest-test_ros_network_ros_network_default.xml" "--return-code" "/opt/ros/melodic/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/sjtuwhl/ROBOTLAB_WS/src/gazebo_ros_pkgs-melodic-devel/gazebo_ros --package=gazebo_ros --results-filename test_ros_network_ros_network_default.xml --results-base-dir \"/home/sjtuwhl/ROBOTLAB_WS/devel/test_results\" /home/sjtuwhl/ROBOTLAB_WS/src/gazebo_ros_pkgs-melodic-devel/gazebo_ros/test/ros_network/ros_network_default.test ")
set_tests_properties(_ctest_gazebo_ros_rostest_test_ros_network_ros_network_default.test PROPERTIES  _BACKTRACE_TRIPLES "/opt/ros/melodic/share/catkin/cmake/test/tests.cmake;143;add_test;/opt/ros/melodic/share/rostest/cmake/rostest-extras.cmake;52;catkin_run_tests_target;/home/sjtuwhl/ROBOTLAB_WS/src/gazebo_ros_pkgs-melodic-devel/gazebo_ros/test/CMakeLists.txt;11;add_rostest;/home/sjtuwhl/ROBOTLAB_WS/src/gazebo_ros_pkgs-melodic-devel/gazebo_ros/test/CMakeLists.txt;0;")
add_test(check_ros_network/ros_network_default.test "rosrun" "rosunit" "check_test_ran.py" "--rostest" "/home/sjtuwhl/ROBOTLAB_WS/src/gazebo_ros_pkgs-melodic-devel/gazebo_ros/test/ros_network/ros_network_default.test")
set_tests_properties(check_ros_network/ros_network_default.test PROPERTIES  _BACKTRACE_TRIPLES "/home/sjtuwhl/ROBOTLAB_WS/src/gazebo_ros_pkgs-melodic-devel/gazebo_ros/test/CMakeLists.txt;14;add_test;/home/sjtuwhl/ROBOTLAB_WS/src/gazebo_ros_pkgs-melodic-devel/gazebo_ros/test/CMakeLists.txt;0;")
add_test(_ctest_gazebo_ros_rostest_test_ros_network_ros_network_disabled.test "/home/sjtuwhl/ROBOTLAB_WS/devel/catkin_generated/env_cached.sh" "/usr/bin/python2" "/opt/ros/melodic/share/catkin/cmake/test/run_tests.py" "/home/sjtuwhl/ROBOTLAB_WS/devel/test_results/gazebo_ros/rostest-test_ros_network_ros_network_disabled.xml" "--return-code" "/opt/ros/melodic/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/sjtuwhl/ROBOTLAB_WS/src/gazebo_ros_pkgs-melodic-devel/gazebo_ros --package=gazebo_ros --results-filename test_ros_network_ros_network_disabled.xml --results-base-dir \"/home/sjtuwhl/ROBOTLAB_WS/devel/test_results\" /home/sjtuwhl/ROBOTLAB_WS/src/gazebo_ros_pkgs-melodic-devel/gazebo_ros/test/ros_network/ros_network_disabled.test ")
set_tests_properties(_ctest_gazebo_ros_rostest_test_ros_network_ros_network_disabled.test PROPERTIES  _BACKTRACE_TRIPLES "/opt/ros/melodic/share/catkin/cmake/test/tests.cmake;143;add_test;/opt/ros/melodic/share/rostest/cmake/rostest-extras.cmake;52;catkin_run_tests_target;/home/sjtuwhl/ROBOTLAB_WS/src/gazebo_ros_pkgs-melodic-devel/gazebo_ros/test/CMakeLists.txt;11;add_rostest;/home/sjtuwhl/ROBOTLAB_WS/src/gazebo_ros_pkgs-melodic-devel/gazebo_ros/test/CMakeLists.txt;0;")
add_test(check_ros_network/ros_network_disabled.test "rosrun" "rosunit" "check_test_ran.py" "--rostest" "/home/sjtuwhl/ROBOTLAB_WS/src/gazebo_ros_pkgs-melodic-devel/gazebo_ros/test/ros_network/ros_network_disabled.test")
set_tests_properties(check_ros_network/ros_network_disabled.test PROPERTIES  _BACKTRACE_TRIPLES "/home/sjtuwhl/ROBOTLAB_WS/src/gazebo_ros_pkgs-melodic-devel/gazebo_ros/test/CMakeLists.txt;14;add_test;/home/sjtuwhl/ROBOTLAB_WS/src/gazebo_ros_pkgs-melodic-devel/gazebo_ros/test/CMakeLists.txt;0;")
