# CMake generated Testfile for 
# Source directory: /home/sjtuwhl/ROBOTLAB_WS/src/scan_tools-indigo/laser_scan_matcher
# Build directory: /home/sjtuwhl/ROBOTLAB_WS/devel/scan_tools-indigo/laser_scan_matcher
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(_ctest_laser_scan_matcher_rostest_test_run.test "/home/sjtuwhl/ROBOTLAB_WS/devel/catkin_generated/env_cached.sh" "/usr/bin/python2" "/opt/ros/melodic/share/catkin/cmake/test/run_tests.py" "/home/sjtuwhl/ROBOTLAB_WS/devel/test_results/laser_scan_matcher/rostest-test_run.xml" "--return-code" "/opt/ros/melodic/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/sjtuwhl/ROBOTLAB_WS/src/scan_tools-indigo/laser_scan_matcher --package=laser_scan_matcher --results-filename test_run.xml --results-base-dir \"/home/sjtuwhl/ROBOTLAB_WS/devel/test_results\" /home/sjtuwhl/ROBOTLAB_WS/src/scan_tools-indigo/laser_scan_matcher/test/run.test ")
set_tests_properties(_ctest_laser_scan_matcher_rostest_test_run.test PROPERTIES  _BACKTRACE_TRIPLES "/opt/ros/melodic/share/catkin/cmake/test/tests.cmake;143;add_test;/opt/ros/melodic/share/rostest/cmake/rostest-extras.cmake;52;catkin_run_tests_target;/home/sjtuwhl/ROBOTLAB_WS/src/scan_tools-indigo/laser_scan_matcher/CMakeLists.txt;71;add_rostest;/home/sjtuwhl/ROBOTLAB_WS/src/scan_tools-indigo/laser_scan_matcher/CMakeLists.txt;0;")
add_test(_ctest_laser_scan_matcher_rostest_test_covariance.test "/home/sjtuwhl/ROBOTLAB_WS/devel/catkin_generated/env_cached.sh" "/usr/bin/python2" "/opt/ros/melodic/share/catkin/cmake/test/run_tests.py" "/home/sjtuwhl/ROBOTLAB_WS/devel/test_results/laser_scan_matcher/rostest-test_covariance.xml" "--return-code" "/opt/ros/melodic/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/sjtuwhl/ROBOTLAB_WS/src/scan_tools-indigo/laser_scan_matcher --package=laser_scan_matcher --results-filename test_covariance.xml --results-base-dir \"/home/sjtuwhl/ROBOTLAB_WS/devel/test_results\" /home/sjtuwhl/ROBOTLAB_WS/src/scan_tools-indigo/laser_scan_matcher/test/covariance.test ")
set_tests_properties(_ctest_laser_scan_matcher_rostest_test_covariance.test PROPERTIES  _BACKTRACE_TRIPLES "/opt/ros/melodic/share/catkin/cmake/test/tests.cmake;143;add_test;/opt/ros/melodic/share/rostest/cmake/rostest-extras.cmake;52;catkin_run_tests_target;/home/sjtuwhl/ROBOTLAB_WS/src/scan_tools-indigo/laser_scan_matcher/CMakeLists.txt;72;add_rostest;/home/sjtuwhl/ROBOTLAB_WS/src/scan_tools-indigo/laser_scan_matcher/CMakeLists.txt;0;")
