# CMake generated Testfile for 
# Source directory: /home/sjtuwhl/ROBOTLAB_WS/src/ros_control-melodic-devel/hardware_interface
# Build directory: /home/sjtuwhl/ROBOTLAB_WS/devel/ros_control-melodic-devel/hardware_interface
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(_ctest_hardware_interface_gtest_hardware_resource_manager_test "/home/sjtuwhl/ROBOTLAB_WS/devel/catkin_generated/env_cached.sh" "/usr/bin/python2" "/opt/ros/melodic/share/catkin/cmake/test/run_tests.py" "/home/sjtuwhl/ROBOTLAB_WS/devel/test_results/hardware_interface/gtest-hardware_resource_manager_test.xml" "--return-code" "/home/sjtuwhl/ROBOTLAB_WS/devel/lib/hardware_interface/hardware_resource_manager_test --gtest_output=xml:/home/sjtuwhl/ROBOTLAB_WS/devel/test_results/hardware_interface/gtest-hardware_resource_manager_test.xml")
set_tests_properties(_ctest_hardware_interface_gtest_hardware_resource_manager_test PROPERTIES  _BACKTRACE_TRIPLES "/opt/ros/melodic/share/catkin/cmake/test/tests.cmake;143;add_test;/opt/ros/melodic/share/catkin/cmake/test/gtest.cmake;89;catkin_run_tests_target;/opt/ros/melodic/share/catkin/cmake/test/gtest.cmake;28;_catkin_add_google_test;/home/sjtuwhl/ROBOTLAB_WS/src/ros_control-melodic-devel/hardware_interface/CMakeLists.txt;17;catkin_add_gtest;/home/sjtuwhl/ROBOTLAB_WS/src/ros_control-melodic-devel/hardware_interface/CMakeLists.txt;0;")
add_test(_ctest_hardware_interface_gtest_actuator_state_interface_test "/home/sjtuwhl/ROBOTLAB_WS/devel/catkin_generated/env_cached.sh" "/usr/bin/python2" "/opt/ros/melodic/share/catkin/cmake/test/run_tests.py" "/home/sjtuwhl/ROBOTLAB_WS/devel/test_results/hardware_interface/gtest-actuator_state_interface_test.xml" "--return-code" "/home/sjtuwhl/ROBOTLAB_WS/devel/lib/hardware_interface/actuator_state_interface_test --gtest_output=xml:/home/sjtuwhl/ROBOTLAB_WS/devel/test_results/hardware_interface/gtest-actuator_state_interface_test.xml")
set_tests_properties(_ctest_hardware_interface_gtest_actuator_state_interface_test PROPERTIES  _BACKTRACE_TRIPLES "/opt/ros/melodic/share/catkin/cmake/test/tests.cmake;143;add_test;/opt/ros/melodic/share/catkin/cmake/test/gtest.cmake;89;catkin_run_tests_target;/opt/ros/melodic/share/catkin/cmake/test/gtest.cmake;28;_catkin_add_google_test;/home/sjtuwhl/ROBOTLAB_WS/src/ros_control-melodic-devel/hardware_interface/CMakeLists.txt;20;catkin_add_gtest;/home/sjtuwhl/ROBOTLAB_WS/src/ros_control-melodic-devel/hardware_interface/CMakeLists.txt;0;")
add_test(_ctest_hardware_interface_gtest_actuator_command_interface_test "/home/sjtuwhl/ROBOTLAB_WS/devel/catkin_generated/env_cached.sh" "/usr/bin/python2" "/opt/ros/melodic/share/catkin/cmake/test/run_tests.py" "/home/sjtuwhl/ROBOTLAB_WS/devel/test_results/hardware_interface/gtest-actuator_command_interface_test.xml" "--return-code" "/home/sjtuwhl/ROBOTLAB_WS/devel/lib/hardware_interface/actuator_command_interface_test --gtest_output=xml:/home/sjtuwhl/ROBOTLAB_WS/devel/test_results/hardware_interface/gtest-actuator_command_interface_test.xml")
set_tests_properties(_ctest_hardware_interface_gtest_actuator_command_interface_test PROPERTIES  _BACKTRACE_TRIPLES "/opt/ros/melodic/share/catkin/cmake/test/tests.cmake;143;add_test;/opt/ros/melodic/share/catkin/cmake/test/gtest.cmake;89;catkin_run_tests_target;/opt/ros/melodic/share/catkin/cmake/test/gtest.cmake;28;_catkin_add_google_test;/home/sjtuwhl/ROBOTLAB_WS/src/ros_control-melodic-devel/hardware_interface/CMakeLists.txt;23;catkin_add_gtest;/home/sjtuwhl/ROBOTLAB_WS/src/ros_control-melodic-devel/hardware_interface/CMakeLists.txt;0;")
add_test(_ctest_hardware_interface_gtest_joint_state_interface_test "/home/sjtuwhl/ROBOTLAB_WS/devel/catkin_generated/env_cached.sh" "/usr/bin/python2" "/opt/ros/melodic/share/catkin/cmake/test/run_tests.py" "/home/sjtuwhl/ROBOTLAB_WS/devel/test_results/hardware_interface/gtest-joint_state_interface_test.xml" "--return-code" "/home/sjtuwhl/ROBOTLAB_WS/devel/lib/hardware_interface/joint_state_interface_test --gtest_output=xml:/home/sjtuwhl/ROBOTLAB_WS/devel/test_results/hardware_interface/gtest-joint_state_interface_test.xml")
set_tests_properties(_ctest_hardware_interface_gtest_joint_state_interface_test PROPERTIES  _BACKTRACE_TRIPLES "/opt/ros/melodic/share/catkin/cmake/test/tests.cmake;143;add_test;/opt/ros/melodic/share/catkin/cmake/test/gtest.cmake;89;catkin_run_tests_target;/opt/ros/melodic/share/catkin/cmake/test/gtest.cmake;28;_catkin_add_google_test;/home/sjtuwhl/ROBOTLAB_WS/src/ros_control-melodic-devel/hardware_interface/CMakeLists.txt;26;catkin_add_gtest;/home/sjtuwhl/ROBOTLAB_WS/src/ros_control-melodic-devel/hardware_interface/CMakeLists.txt;0;")
add_test(_ctest_hardware_interface_gtest_joint_command_interface_test "/home/sjtuwhl/ROBOTLAB_WS/devel/catkin_generated/env_cached.sh" "/usr/bin/python2" "/opt/ros/melodic/share/catkin/cmake/test/run_tests.py" "/home/sjtuwhl/ROBOTLAB_WS/devel/test_results/hardware_interface/gtest-joint_command_interface_test.xml" "--return-code" "/home/sjtuwhl/ROBOTLAB_WS/devel/lib/hardware_interface/joint_command_interface_test --gtest_output=xml:/home/sjtuwhl/ROBOTLAB_WS/devel/test_results/hardware_interface/gtest-joint_command_interface_test.xml")
set_tests_properties(_ctest_hardware_interface_gtest_joint_command_interface_test PROPERTIES  _BACKTRACE_TRIPLES "/opt/ros/melodic/share/catkin/cmake/test/tests.cmake;143;add_test;/opt/ros/melodic/share/catkin/cmake/test/gtest.cmake;89;catkin_run_tests_target;/opt/ros/melodic/share/catkin/cmake/test/gtest.cmake;28;_catkin_add_google_test;/home/sjtuwhl/ROBOTLAB_WS/src/ros_control-melodic-devel/hardware_interface/CMakeLists.txt;29;catkin_add_gtest;/home/sjtuwhl/ROBOTLAB_WS/src/ros_control-melodic-devel/hardware_interface/CMakeLists.txt;0;")
add_test(_ctest_hardware_interface_gtest_force_torque_sensor_interface_test "/home/sjtuwhl/ROBOTLAB_WS/devel/catkin_generated/env_cached.sh" "/usr/bin/python2" "/opt/ros/melodic/share/catkin/cmake/test/run_tests.py" "/home/sjtuwhl/ROBOTLAB_WS/devel/test_results/hardware_interface/gtest-force_torque_sensor_interface_test.xml" "--return-code" "/home/sjtuwhl/ROBOTLAB_WS/devel/lib/hardware_interface/force_torque_sensor_interface_test --gtest_output=xml:/home/sjtuwhl/ROBOTLAB_WS/devel/test_results/hardware_interface/gtest-force_torque_sensor_interface_test.xml")
set_tests_properties(_ctest_hardware_interface_gtest_force_torque_sensor_interface_test PROPERTIES  _BACKTRACE_TRIPLES "/opt/ros/melodic/share/catkin/cmake/test/tests.cmake;143;add_test;/opt/ros/melodic/share/catkin/cmake/test/gtest.cmake;89;catkin_run_tests_target;/opt/ros/melodic/share/catkin/cmake/test/gtest.cmake;28;_catkin_add_google_test;/home/sjtuwhl/ROBOTLAB_WS/src/ros_control-melodic-devel/hardware_interface/CMakeLists.txt;32;catkin_add_gtest;/home/sjtuwhl/ROBOTLAB_WS/src/ros_control-melodic-devel/hardware_interface/CMakeLists.txt;0;")
add_test(_ctest_hardware_interface_gtest_imu_sensor_interface_test "/home/sjtuwhl/ROBOTLAB_WS/devel/catkin_generated/env_cached.sh" "/usr/bin/python2" "/opt/ros/melodic/share/catkin/cmake/test/run_tests.py" "/home/sjtuwhl/ROBOTLAB_WS/devel/test_results/hardware_interface/gtest-imu_sensor_interface_test.xml" "--return-code" "/home/sjtuwhl/ROBOTLAB_WS/devel/lib/hardware_interface/imu_sensor_interface_test --gtest_output=xml:/home/sjtuwhl/ROBOTLAB_WS/devel/test_results/hardware_interface/gtest-imu_sensor_interface_test.xml")
set_tests_properties(_ctest_hardware_interface_gtest_imu_sensor_interface_test PROPERTIES  _BACKTRACE_TRIPLES "/opt/ros/melodic/share/catkin/cmake/test/tests.cmake;143;add_test;/opt/ros/melodic/share/catkin/cmake/test/gtest.cmake;89;catkin_run_tests_target;/opt/ros/melodic/share/catkin/cmake/test/gtest.cmake;28;_catkin_add_google_test;/home/sjtuwhl/ROBOTLAB_WS/src/ros_control-melodic-devel/hardware_interface/CMakeLists.txt;35;catkin_add_gtest;/home/sjtuwhl/ROBOTLAB_WS/src/ros_control-melodic-devel/hardware_interface/CMakeLists.txt;0;")
add_test(_ctest_hardware_interface_gtest_robot_hw_test "/home/sjtuwhl/ROBOTLAB_WS/devel/catkin_generated/env_cached.sh" "/usr/bin/python2" "/opt/ros/melodic/share/catkin/cmake/test/run_tests.py" "/home/sjtuwhl/ROBOTLAB_WS/devel/test_results/hardware_interface/gtest-robot_hw_test.xml" "--return-code" "/home/sjtuwhl/ROBOTLAB_WS/devel/lib/hardware_interface/robot_hw_test --gtest_output=xml:/home/sjtuwhl/ROBOTLAB_WS/devel/test_results/hardware_interface/gtest-robot_hw_test.xml")
set_tests_properties(_ctest_hardware_interface_gtest_robot_hw_test PROPERTIES  _BACKTRACE_TRIPLES "/opt/ros/melodic/share/catkin/cmake/test/tests.cmake;143;add_test;/opt/ros/melodic/share/catkin/cmake/test/gtest.cmake;89;catkin_run_tests_target;/opt/ros/melodic/share/catkin/cmake/test/gtest.cmake;28;_catkin_add_google_test;/home/sjtuwhl/ROBOTLAB_WS/src/ros_control-melodic-devel/hardware_interface/CMakeLists.txt;38;catkin_add_gtest;/home/sjtuwhl/ROBOTLAB_WS/src/ros_control-melodic-devel/hardware_interface/CMakeLists.txt;0;")
add_test(_ctest_hardware_interface_gtest_interface_manager_test "/home/sjtuwhl/ROBOTLAB_WS/devel/catkin_generated/env_cached.sh" "/usr/bin/python2" "/opt/ros/melodic/share/catkin/cmake/test/run_tests.py" "/home/sjtuwhl/ROBOTLAB_WS/devel/test_results/hardware_interface/gtest-interface_manager_test.xml" "--return-code" "/home/sjtuwhl/ROBOTLAB_WS/devel/lib/hardware_interface/interface_manager_test --gtest_output=xml:/home/sjtuwhl/ROBOTLAB_WS/devel/test_results/hardware_interface/gtest-interface_manager_test.xml")
set_tests_properties(_ctest_hardware_interface_gtest_interface_manager_test PROPERTIES  _BACKTRACE_TRIPLES "/opt/ros/melodic/share/catkin/cmake/test/tests.cmake;143;add_test;/opt/ros/melodic/share/catkin/cmake/test/gtest.cmake;89;catkin_run_tests_target;/opt/ros/melodic/share/catkin/cmake/test/gtest.cmake;28;_catkin_add_google_test;/home/sjtuwhl/ROBOTLAB_WS/src/ros_control-melodic-devel/hardware_interface/CMakeLists.txt;41;catkin_add_gtest;/home/sjtuwhl/ROBOTLAB_WS/src/ros_control-melodic-devel/hardware_interface/CMakeLists.txt;0;")
add_test(_ctest_hardware_interface_gtest_posvel_command_interface_test "/home/sjtuwhl/ROBOTLAB_WS/devel/catkin_generated/env_cached.sh" "/usr/bin/python2" "/opt/ros/melodic/share/catkin/cmake/test/run_tests.py" "/home/sjtuwhl/ROBOTLAB_WS/devel/test_results/hardware_interface/gtest-posvel_command_interface_test.xml" "--return-code" "/home/sjtuwhl/ROBOTLAB_WS/devel/lib/hardware_interface/posvel_command_interface_test --gtest_output=xml:/home/sjtuwhl/ROBOTLAB_WS/devel/test_results/hardware_interface/gtest-posvel_command_interface_test.xml")
set_tests_properties(_ctest_hardware_interface_gtest_posvel_command_interface_test PROPERTIES  _BACKTRACE_TRIPLES "/opt/ros/melodic/share/catkin/cmake/test/tests.cmake;143;add_test;/opt/ros/melodic/share/catkin/cmake/test/gtest.cmake;89;catkin_run_tests_target;/opt/ros/melodic/share/catkin/cmake/test/gtest.cmake;28;_catkin_add_google_test;/home/sjtuwhl/ROBOTLAB_WS/src/ros_control-melodic-devel/hardware_interface/CMakeLists.txt;44;catkin_add_gtest;/home/sjtuwhl/ROBOTLAB_WS/src/ros_control-melodic-devel/hardware_interface/CMakeLists.txt;0;")
add_test(_ctest_hardware_interface_gtest_posvelacc_command_interface_test "/home/sjtuwhl/ROBOTLAB_WS/devel/catkin_generated/env_cached.sh" "/usr/bin/python2" "/opt/ros/melodic/share/catkin/cmake/test/run_tests.py" "/home/sjtuwhl/ROBOTLAB_WS/devel/test_results/hardware_interface/gtest-posvelacc_command_interface_test.xml" "--return-code" "/home/sjtuwhl/ROBOTLAB_WS/devel/lib/hardware_interface/posvelacc_command_interface_test --gtest_output=xml:/home/sjtuwhl/ROBOTLAB_WS/devel/test_results/hardware_interface/gtest-posvelacc_command_interface_test.xml")
set_tests_properties(_ctest_hardware_interface_gtest_posvelacc_command_interface_test PROPERTIES  _BACKTRACE_TRIPLES "/opt/ros/melodic/share/catkin/cmake/test/tests.cmake;143;add_test;/opt/ros/melodic/share/catkin/cmake/test/gtest.cmake;89;catkin_run_tests_target;/opt/ros/melodic/share/catkin/cmake/test/gtest.cmake;28;_catkin_add_google_test;/home/sjtuwhl/ROBOTLAB_WS/src/ros_control-melodic-devel/hardware_interface/CMakeLists.txt;47;catkin_add_gtest;/home/sjtuwhl/ROBOTLAB_WS/src/ros_control-melodic-devel/hardware_interface/CMakeLists.txt;0;")
