set(_CATKIN_CURRENT_PACKAGE "my_laser_matcher")
set(my_laser_matcher_VERSION "0.0.0")
set(my_laser_matcher_MAINTAINER "sjtuwhl <sjtuwhl@todo.todo>")
set(my_laser_matcher_PACKAGE_FORMAT "2")
set(my_laser_matcher_BUILD_DEPENDS )
set(my_laser_matcher_BUILD_EXPORT_DEPENDS )
set(my_laser_matcher_BUILDTOOL_DEPENDS "catkin")
set(my_laser_matcher_BUILDTOOL_EXPORT_DEPENDS )
set(my_laser_matcher_EXEC_DEPENDS )
set(my_laser_matcher_RUN_DEPENDS )
set(my_laser_matcher_TEST_DEPENDS )
set(my_laser_matcher_DOC_DEPENDS )
set(my_laser_matcher_URL_WEBSITE "")
set(my_laser_matcher_URL_BUGTRACKER "")
set(my_laser_matcher_URL_REPOSITORY "")
set(my_laser_matcher_DEPRECATED "")