# CMake generated Testfile for 
# Source directory: /home/sjtuwhl/ROBOTLAB_WS/src/ros_control-melodic-devel/combined_robot_hw_tests
# Build directory: /home/sjtuwhl/ROBOTLAB_WS/devel/ros_control-melodic-devel/combined_robot_hw_tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(_ctest_combined_robot_hw_tests_rostest_test_combined_robot_hw_test.test "/home/sjtuwhl/ROBOTLAB_WS/devel/catkin_generated/env_cached.sh" "/usr/bin/python2" "/opt/ros/melodic/share/catkin/cmake/test/run_tests.py" "/home/sjtuwhl/ROBOTLAB_WS/devel/test_results/combined_robot_hw_tests/rostest-test_combined_robot_hw_test.xml" "--return-code" "/opt/ros/melodic/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/sjtuwhl/ROBOTLAB_WS/src/ros_control-melodic-devel/combined_robot_hw_tests --package=combined_robot_hw_tests --results-filename test_combined_robot_hw_test.xml --results-base-dir \"/home/sjtuwhl/ROBOTLAB_WS/devel/test_results\" /home/sjtuwhl/ROBOTLAB_WS/src/ros_control-melodic-devel/combined_robot_hw_tests/test/combined_robot_hw_test.test ")
set_tests_properties(_ctest_combined_robot_hw_tests_rostest_test_combined_robot_hw_test.test PROPERTIES  _BACKTRACE_TRIPLES "/opt/ros/melodic/share/catkin/cmake/test/tests.cmake;143;add_test;/opt/ros/melodic/share/rostest/cmake/rostest-extras.cmake;52;catkin_run_tests_target;/opt/ros/melodic/share/rostest/cmake/rostest-extras.cmake;80;add_rostest;/opt/ros/melodic/share/rostest/cmake/rostest-extras.cmake;100;_add_rostest_google_test;/home/sjtuwhl/ROBOTLAB_WS/src/ros_control-melodic-devel/combined_robot_hw_tests/CMakeLists.txt;38;add_rostest_gtest;/home/sjtuwhl/ROBOTLAB_WS/src/ros_control-melodic-devel/combined_robot_hw_tests/CMakeLists.txt;0;")
add_test(_ctest_combined_robot_hw_tests_rostest_test_cm_test.test "/home/sjtuwhl/ROBOTLAB_WS/devel/catkin_generated/env_cached.sh" "/usr/bin/python2" "/opt/ros/melodic/share/catkin/cmake/test/run_tests.py" "/home/sjtuwhl/ROBOTLAB_WS/devel/test_results/combined_robot_hw_tests/rostest-test_cm_test.xml" "--return-code" "/opt/ros/melodic/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/sjtuwhl/ROBOTLAB_WS/src/ros_control-melodic-devel/combined_robot_hw_tests --package=combined_robot_hw_tests --results-filename test_cm_test.xml --results-base-dir \"/home/sjtuwhl/ROBOTLAB_WS/devel/test_results\" /home/sjtuwhl/ROBOTLAB_WS/src/ros_control-melodic-devel/combined_robot_hw_tests/test/cm_test.test ")
set_tests_properties(_ctest_combined_robot_hw_tests_rostest_test_cm_test.test PROPERTIES  _BACKTRACE_TRIPLES "/opt/ros/melodic/share/catkin/cmake/test/tests.cmake;143;add_test;/opt/ros/melodic/share/rostest/cmake/rostest-extras.cmake;52;catkin_run_tests_target;/opt/ros/melodic/share/rostest/cmake/rostest-extras.cmake;80;add_rostest;/opt/ros/melodic/share/rostest/cmake/rostest-extras.cmake;100;_add_rostest_google_test;/home/sjtuwhl/ROBOTLAB_WS/src/ros_control-melodic-devel/combined_robot_hw_tests/CMakeLists.txt;44;add_rostest_gtest;/home/sjtuwhl/ROBOTLAB_WS/src/ros_control-melodic-devel/combined_robot_hw_tests/CMakeLists.txt;0;")
