set(_CATKIN_CURRENT_PACKAGE "agv_model")
set(agv_model_VERSION "0.0.0")
set(agv_model_MAINTAINER "hxq <hxq@todo.todo>")
set(agv_model_PACKAGE_FORMAT "2")
set(agv_model_BUILD_DEPENDS "roscpp" "rospy" "std_msgs")
set(agv_model_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "std_msgs")
set(agv_model_BUILDTOOL_DEPENDS "catkin")
set(agv_model_BUILDTOOL_EXPORT_DEPENDS )
set(agv_model_EXEC_DEPENDS "roscpp" "rospy" "std_msgs")
set(agv_model_RUN_DEPENDS "roscpp" "rospy" "std_msgs")
set(agv_model_TEST_DEPENDS )
set(agv_model_DOC_DEPENDS )
set(agv_model_URL_WEBSITE "")
set(agv_model_URL_BUGTRACKER "")
set(agv_model_URL_REPOSITORY "")
set(agv_model_DEPRECATED "")