set(_CATKIN_CURRENT_PACKAGE "soccer_maxon")
set(soccer_maxon_VERSION "0.0.0")
set(soccer_maxon_MAINTAINER "amigo <amigo@todo.todo>")
set(soccer_maxon_PACKAGE_FORMAT "1")
set(soccer_maxon_BUILD_DEPENDS "geometry_msgs" "roscpp")
set(soccer_maxon_BUILD_EXPORT_DEPENDS "geometry_msgs" "roscpp")
set(soccer_maxon_BUILDTOOL_DEPENDS "catkin")
set(soccer_maxon_BUILDTOOL_EXPORT_DEPENDS )
set(soccer_maxon_EXEC_DEPENDS "geometry_msgs" "roscpp")
set(soccer_maxon_RUN_DEPENDS "geometry_msgs" "roscpp")
set(soccer_maxon_TEST_DEPENDS )
set(soccer_maxon_DOC_DEPENDS )
set(soccer_maxon_URL_WEBSITE "")
set(soccer_maxon_URL_BUGTRACKER "")
set(soccer_maxon_URL_REPOSITORY "")
set(soccer_maxon_DEPRECATED "")