set(_CATKIN_CURRENT_PACKAGE "agv_udp")
set(agv_udp_VERSION "0.0.0")
set(agv_udp_MAINTAINER "huang <huang@todo.todo>")
set(agv_udp_PACKAGE_FORMAT "2")
set(agv_udp_BUILD_DEPENDS "message_generation" "roscpp" "rosmsg" "rospy" "rossrv")
set(agv_udp_BUILD_EXPORT_DEPENDS "roscpp" "rosmsg" "rospy" "rossrv")
set(agv_udp_BUILDTOOL_DEPENDS "catkin")
set(agv_udp_BUILDTOOL_EXPORT_DEPENDS )
set(agv_udp_EXEC_DEPENDS "message_runtime" "roscpp" "rosmsg" "rospy" "rossrv")
set(agv_udp_RUN_DEPENDS "message_runtime" "roscpp" "rosmsg" "rospy" "rossrv")
set(agv_udp_TEST_DEPENDS )
set(agv_udp_DOC_DEPENDS )
set(agv_udp_URL_WEBSITE "")
set(agv_udp_URL_BUGTRACKER "")
set(agv_udp_URL_REPOSITORY "")
set(agv_udp_DEPRECATED "")