// Generated by gencpp from file agv_udp/ReplanRequest.msg
// DO NOT EDIT!


#ifndef AGV_UDP_MESSAGE_REPLANREQUEST_H
#define AGV_UDP_MESSAGE_REPLANREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace agv_udp
{
template <class ContainerAllocator>
struct ReplanRequest_
{
  typedef ReplanRequest_<ContainerAllocator> Type;

  ReplanRequest_()
    : replan(false)
    , robot_index(0)  {
    }
  ReplanRequest_(const ContainerAllocator& _alloc)
    : replan(false)
    , robot_index(0)  {
  (void)_alloc;
    }



   typedef uint8_t _replan_type;
  _replan_type replan;

   typedef uint32_t _robot_index_type;
  _robot_index_type robot_index;





  typedef boost::shared_ptr< ::agv_udp::ReplanRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::agv_udp::ReplanRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ReplanRequest_

typedef ::agv_udp::ReplanRequest_<std::allocator<void> > ReplanRequest;

typedef boost::shared_ptr< ::agv_udp::ReplanRequest > ReplanRequestPtr;
typedef boost::shared_ptr< ::agv_udp::ReplanRequest const> ReplanRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::agv_udp::ReplanRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::agv_udp::ReplanRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace agv_udp

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'agv_udp': ['/home/sjtuwhl/ROBOTLAB_WS/src/agv_udp/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::agv_udp::ReplanRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::agv_udp::ReplanRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::agv_udp::ReplanRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::agv_udp::ReplanRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::agv_udp::ReplanRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::agv_udp::ReplanRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::agv_udp::ReplanRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5cf4d38b1baf82787e4c474ad9cb888c";
  }

  static const char* value(const ::agv_udp::ReplanRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5cf4d38b1baf8278ULL;
  static const uint64_t static_value2 = 0x7e4c474ad9cb888cULL;
};

template<class ContainerAllocator>
struct DataType< ::agv_udp::ReplanRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "agv_udp/ReplanRequest";
  }

  static const char* value(const ::agv_udp::ReplanRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::agv_udp::ReplanRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool replan\n"
"uint32 robot_index\n"
;
  }

  static const char* value(const ::agv_udp::ReplanRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::agv_udp::ReplanRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.replan);
      stream.next(m.robot_index);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ReplanRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::agv_udp::ReplanRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::agv_udp::ReplanRequest_<ContainerAllocator>& v)
  {
    s << indent << "replan: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.replan);
    s << indent << "robot_index: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.robot_index);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AGV_UDP_MESSAGE_REPLANREQUEST_H
