// Generated by gencpp from file agv_udp/Replan.msg
// DO NOT EDIT!


#ifndef AGV_UDP_MESSAGE_REPLAN_H
#define AGV_UDP_MESSAGE_REPLAN_H

#include <ros/service_traits.h>


#include <agv_udp/ReplanRequest.h>
#include <agv_udp/ReplanResponse.h>


namespace agv_udp
{

struct Replan
{

typedef ReplanRequest Request;
typedef ReplanResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Replan
} // namespace agv_udp


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::agv_udp::Replan > {
  static const char* value()
  {
    return "e04b284656e20206941686c48843bad8";
  }

  static const char* value(const ::agv_udp::Replan&) { return value(); }
};

template<>
struct DataType< ::agv_udp::Replan > {
  static const char* value()
  {
    return "agv_udp/Replan";
  }

  static const char* value(const ::agv_udp::Replan&) { return value(); }
};


// service_traits::MD5Sum< ::agv_udp::ReplanRequest> should match 
// service_traits::MD5Sum< ::agv_udp::Replan > 
template<>
struct MD5Sum< ::agv_udp::ReplanRequest>
{
  static const char* value()
  {
    return MD5Sum< ::agv_udp::Replan >::value();
  }
  static const char* value(const ::agv_udp::ReplanRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::agv_udp::ReplanRequest> should match 
// service_traits::DataType< ::agv_udp::Replan > 
template<>
struct DataType< ::agv_udp::ReplanRequest>
{
  static const char* value()
  {
    return DataType< ::agv_udp::Replan >::value();
  }
  static const char* value(const ::agv_udp::ReplanRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::agv_udp::ReplanResponse> should match 
// service_traits::MD5Sum< ::agv_udp::Replan > 
template<>
struct MD5Sum< ::agv_udp::ReplanResponse>
{
  static const char* value()
  {
    return MD5Sum< ::agv_udp::Replan >::value();
  }
  static const char* value(const ::agv_udp::ReplanResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::agv_udp::ReplanResponse> should match 
// service_traits::DataType< ::agv_udp::Replan > 
template<>
struct DataType< ::agv_udp::ReplanResponse>
{
  static const char* value()
  {
    return DataType< ::agv_udp::Replan >::value();
  }
  static const char* value(const ::agv_udp::ReplanResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // AGV_UDP_MESSAGE_REPLAN_H
