// Generated by gencpp from file move_forward/agv_call.msg
// DO NOT EDIT!


#ifndef MOVE_FORWARD_MESSAGE_AGV_CALL_H
#define MOVE_FORWARD_MESSAGE_AGV_CALL_H

#include <ros/service_traits.h>


#include <move_forward/agv_callRequest.h>
#include <move_forward/agv_callResponse.h>


namespace move_forward
{

struct agv_call
{

typedef agv_callRequest Request;
typedef agv_callResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct agv_call
} // namespace move_forward


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::move_forward::agv_call > {
  static const char* value()
  {
    return "bbdd7d6a90f6922f6aae5a0ca449c65d";
  }

  static const char* value(const ::move_forward::agv_call&) { return value(); }
};

template<>
struct DataType< ::move_forward::agv_call > {
  static const char* value()
  {
    return "move_forward/agv_call";
  }

  static const char* value(const ::move_forward::agv_call&) { return value(); }
};


// service_traits::MD5Sum< ::move_forward::agv_callRequest> should match 
// service_traits::MD5Sum< ::move_forward::agv_call > 
template<>
struct MD5Sum< ::move_forward::agv_callRequest>
{
  static const char* value()
  {
    return MD5Sum< ::move_forward::agv_call >::value();
  }
  static const char* value(const ::move_forward::agv_callRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::move_forward::agv_callRequest> should match 
// service_traits::DataType< ::move_forward::agv_call > 
template<>
struct DataType< ::move_forward::agv_callRequest>
{
  static const char* value()
  {
    return DataType< ::move_forward::agv_call >::value();
  }
  static const char* value(const ::move_forward::agv_callRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::move_forward::agv_callResponse> should match 
// service_traits::MD5Sum< ::move_forward::agv_call > 
template<>
struct MD5Sum< ::move_forward::agv_callResponse>
{
  static const char* value()
  {
    return MD5Sum< ::move_forward::agv_call >::value();
  }
  static const char* value(const ::move_forward::agv_callResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::move_forward::agv_callResponse> should match 
// service_traits::DataType< ::move_forward::agv_call > 
template<>
struct DataType< ::move_forward::agv_callResponse>
{
  static const char* value()
  {
    return DataType< ::move_forward::agv_call >::value();
  }
  static const char* value(const ::move_forward::agv_callResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MOVE_FORWARD_MESSAGE_AGV_CALL_H
