# CMake generated Testfile for 
# Source directory: /home/sjtuwhl/ROBOTLAB_WS/src/ros_control-melodic-devel/controller_manager_tests
# Build directory: /home/sjtuwhl/ROBOTLAB_WS/devel/ros_control-melodic-devel/controller_manager_tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(_ctest_controller_manager_tests_rostest_test_cm_test.test "/home/sjtuwhl/ROBOTLAB_WS/devel/catkin_generated/env_cached.sh" "/usr/bin/python2" "/opt/ros/melodic/share/catkin/cmake/test/run_tests.py" "/home/sjtuwhl/ROBOTLAB_WS/devel/test_results/controller_manager_tests/rostest-test_cm_test.xml" "--return-code" "/opt/ros/melodic/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/sjtuwhl/ROBOTLAB_WS/src/ros_control-melodic-devel/controller_manager_tests --package=controller_manager_tests --results-filename test_cm_test.xml --results-base-dir \"/home/sjtuwhl/ROBOTLAB_WS/devel/test_results\" /home/sjtuwhl/ROBOTLAB_WS/src/ros_control-melodic-devel/controller_manager_tests/test/cm_test.test ")
set_tests_properties(_ctest_controller_manager_tests_rostest_test_cm_test.test PROPERTIES  _BACKTRACE_TRIPLES "/opt/ros/melodic/share/catkin/cmake/test/tests.cmake;143;add_test;/opt/ros/melodic/share/rostest/cmake/rostest-extras.cmake;52;catkin_run_tests_target;/home/sjtuwhl/ROBOTLAB_WS/src/ros_control-melodic-devel/controller_manager_tests/CMakeLists.txt;36;add_rostest;/home/sjtuwhl/ROBOTLAB_WS/src/ros_control-melodic-devel/controller_manager_tests/CMakeLists.txt;0;")
add_test(_ctest_controller_manager_tests_nosetests_test "/home/sjtuwhl/ROBOTLAB_WS/devel/catkin_generated/env_cached.sh" "/usr/bin/python2" "/opt/ros/melodic/share/catkin/cmake/test/run_tests.py" "/home/sjtuwhl/ROBOTLAB_WS/devel/test_results/controller_manager_tests/nosetests-test.xml" "--return-code" "\"/home/sjtuwhl/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/192.7142.39/bin/cmake/linux/bin/cmake\" -E make_directory /home/sjtuwhl/ROBOTLAB_WS/devel/test_results/controller_manager_tests" "/usr/bin/nosetests-2.7 -P --process-timeout=60 --where=/home/sjtuwhl/ROBOTLAB_WS/src/ros_control-melodic-devel/controller_manager_tests/test --with-xunit --xunit-file=/home/sjtuwhl/ROBOTLAB_WS/devel/test_results/controller_manager_tests/nosetests-test.xml")
set_tests_properties(_ctest_controller_manager_tests_nosetests_test PROPERTIES  _BACKTRACE_TRIPLES "/opt/ros/melodic/share/catkin/cmake/test/tests.cmake;143;add_test;/opt/ros/melodic/share/catkin/cmake/test/nosetests.cmake;83;catkin_run_tests_target;/home/sjtuwhl/ROBOTLAB_WS/src/ros_control-melodic-devel/controller_manager_tests/CMakeLists.txt;37;catkin_add_nosetests;/home/sjtuwhl/ROBOTLAB_WS/src/ros_control-melodic-devel/controller_manager_tests/CMakeLists.txt;0;")
add_test(_ctest_controller_manager_tests_rostest_test_cm_msgs_utils_rostest.test "/home/sjtuwhl/ROBOTLAB_WS/devel/catkin_generated/env_cached.sh" "/usr/bin/python2" "/opt/ros/melodic/share/catkin/cmake/test/run_tests.py" "/home/sjtuwhl/ROBOTLAB_WS/devel/test_results/controller_manager_tests/rostest-test_cm_msgs_utils_rostest.xml" "--return-code" "/opt/ros/melodic/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/sjtuwhl/ROBOTLAB_WS/src/ros_control-melodic-devel/controller_manager_tests --package=controller_manager_tests --results-filename test_cm_msgs_utils_rostest.xml --results-base-dir \"/home/sjtuwhl/ROBOTLAB_WS/devel/test_results\" /home/sjtuwhl/ROBOTLAB_WS/src/ros_control-melodic-devel/controller_manager_tests/test/cm_msgs_utils_rostest.test ")
set_tests_properties(_ctest_controller_manager_tests_rostest_test_cm_msgs_utils_rostest.test PROPERTIES  _BACKTRACE_TRIPLES "/opt/ros/melodic/share/catkin/cmake/test/tests.cmake;143;add_test;/opt/ros/melodic/share/rostest/cmake/rostest-extras.cmake;52;catkin_run_tests_target;/home/sjtuwhl/ROBOTLAB_WS/src/ros_control-melodic-devel/controller_manager_tests/CMakeLists.txt;38;add_rostest;/home/sjtuwhl/ROBOTLAB_WS/src/ros_control-melodic-devel/controller_manager_tests/CMakeLists.txt;0;")
add_test(_ctest_controller_manager_tests_rostest_test_controller_manager_scripts.test "/home/sjtuwhl/ROBOTLAB_WS/devel/catkin_generated/env_cached.sh" "/usr/bin/python2" "/opt/ros/melodic/share/catkin/cmake/test/run_tests.py" "/home/sjtuwhl/ROBOTLAB_WS/devel/test_results/controller_manager_tests/rostest-test_controller_manager_scripts.xml" "--return-code" "/opt/ros/melodic/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/sjtuwhl/ROBOTLAB_WS/src/ros_control-melodic-devel/controller_manager_tests --package=controller_manager_tests --results-filename test_controller_manager_scripts.xml --results-base-dir \"/home/sjtuwhl/ROBOTLAB_WS/devel/test_results\" /home/sjtuwhl/ROBOTLAB_WS/src/ros_control-melodic-devel/controller_manager_tests/test/controller_manager_scripts.test ")
set_tests_properties(_ctest_controller_manager_tests_rostest_test_controller_manager_scripts.test PROPERTIES  _BACKTRACE_TRIPLES "/opt/ros/melodic/share/catkin/cmake/test/tests.cmake;143;add_test;/opt/ros/melodic/share/rostest/cmake/rostest-extras.cmake;52;catkin_run_tests_target;/home/sjtuwhl/ROBOTLAB_WS/src/ros_control-melodic-devel/controller_manager_tests/CMakeLists.txt;39;add_rostest;/home/sjtuwhl/ROBOTLAB_WS/src/ros_control-melodic-devel/controller_manager_tests/CMakeLists.txt;0;")
