# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from agv_udp/CenterCmd.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class CenterCmd(genpy.Message):
  _md5sum = "1f2758a33326e770ef3efda627a683a4"
  _type = "agv_udp/CenterCmd"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """bool[]  replan
int32[] reserve_area_first
int32[] reserve_area_second
"""
  __slots__ = ['replan','reserve_area_first','reserve_area_second']
  _slot_types = ['bool[]','int32[]','int32[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       replan,reserve_area_first,reserve_area_second

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(CenterCmd, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.replan is None:
        self.replan = []
      if self.reserve_area_first is None:
        self.reserve_area_first = []
      if self.reserve_area_second is None:
        self.reserve_area_second = []
    else:
      self.replan = []
      self.reserve_area_first = []
      self.reserve_area_second = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      length = len(self.replan)
      buff.write(_struct_I.pack(length))
      pattern = '<%sB'%length
      buff.write(struct.pack(pattern, *self.replan))
      length = len(self.reserve_area_first)
      buff.write(_struct_I.pack(length))
      pattern = '<%si'%length
      buff.write(struct.pack(pattern, *self.reserve_area_first))
      length = len(self.reserve_area_second)
      buff.write(_struct_I.pack(length))
      pattern = '<%si'%length
      buff.write(struct.pack(pattern, *self.reserve_area_second))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sB'%length
      start = end
      end += struct.calcsize(pattern)
      self.replan = struct.unpack(pattern, str[start:end])
      self.replan = list(map(bool, self.replan))
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%si'%length
      start = end
      end += struct.calcsize(pattern)
      self.reserve_area_first = struct.unpack(pattern, str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%si'%length
      start = end
      end += struct.calcsize(pattern)
      self.reserve_area_second = struct.unpack(pattern, str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      length = len(self.replan)
      buff.write(_struct_I.pack(length))
      pattern = '<%sB'%length
      buff.write(self.replan.tostring())
      length = len(self.reserve_area_first)
      buff.write(_struct_I.pack(length))
      pattern = '<%si'%length
      buff.write(self.reserve_area_first.tostring())
      length = len(self.reserve_area_second)
      buff.write(_struct_I.pack(length))
      pattern = '<%si'%length
      buff.write(self.reserve_area_second.tostring())
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sB'%length
      start = end
      end += struct.calcsize(pattern)
      self.replan = numpy.frombuffer(str[start:end], dtype=numpy.bool, count=length)
      self.replan = list(map(bool, self.replan))
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%si'%length
      start = end
      end += struct.calcsize(pattern)
      self.reserve_area_first = numpy.frombuffer(str[start:end], dtype=numpy.int32, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%si'%length
      start = end
      end += struct.calcsize(pattern)
      self.reserve_area_second = numpy.frombuffer(str[start:end], dtype=numpy.int32, count=length)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
