# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from agv_udp/ReserveArea.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class ReserveArea(genpy.Message):
  _md5sum = "c22270ab7b7fd72c83a94fc322460280"
  _type = "agv_udp/ReserveArea"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """uint32 first_area
uint32 second_area
bool is_dest
"""
  __slots__ = ['first_area','second_area','is_dest']
  _slot_types = ['uint32','uint32','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       first_area,second_area,is_dest

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(ReserveArea, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.first_area is None:
        self.first_area = 0
      if self.second_area is None:
        self.second_area = 0
      if self.is_dest is None:
        self.is_dest = False
    else:
      self.first_area = 0
      self.second_area = 0
      self.is_dest = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_2IB().pack(_x.first_area, _x.second_area, _x.is_dest))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 9
      (_x.first_area, _x.second_area, _x.is_dest,) = _get_struct_2IB().unpack(str[start:end])
      self.is_dest = bool(self.is_dest)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_2IB().pack(_x.first_area, _x.second_area, _x.is_dest))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 9
      (_x.first_area, _x.second_area, _x.is_dest,) = _get_struct_2IB().unpack(str[start:end])
      self.is_dest = bool(self.is_dest)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2IB = None
def _get_struct_2IB():
    global _struct_2IB
    if _struct_2IB is None:
        _struct_2IB = struct.Struct("<2IB")
    return _struct_2IB
