# CMake generated Testfile for 
# Source directory: /home/sjtuwhl/ROBOTLAB_WS/src
# Build directory: /home/sjtuwhl/ROBOTLAB_WS/devel
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
subdirs("gtest")
subdirs("gazebo_ros_pkgs-melodic-devel/gazebo_dev")
subdirs("gazebo_ros_pkgs-melodic-devel/gazebo_ros_pkgs")
subdirs("move_forward")
subdirs("ros_control-melodic-devel/ros_control")
subdirs("ros_control-melodic-devel/rqt_controller_manager")
subdirs("scan_tools-indigo/scan_tools")
subdirs("ros_control-melodic-devel/controller_manager_msgs")
subdirs("turtlebot3-melodic-devel/turtlebot3")
subdirs("turtlebot3_msgs-melodic-devel")
subdirs("turtlebot3-melodic-devel/turtlebot3_navigation")
subdirs("turtlebot3_simulations-melodic-devel/turtlebot3_simulations")
subdirs("urg_c-master")
subdirs("agv_tcp_velocity")
subdirs("ros_control-melodic-devel/hardware_interface")
subdirs("ros_control-melodic-devel/combined_robot_hw")
subdirs("ros_control-melodic-devel/controller_interface")
subdirs("ros_control-melodic-devel/controller_manager")
subdirs("soccer_maxon")
subdirs("agv_udp")
subdirs("ros_control-melodic-devel/controller_manager_tests")
subdirs("ros_control-melodic-devel/combined_robot_hw_tests")
subdirs("gazebo_ros_pkgs-melodic-devel/gazebo_msgs")
subdirs("laser_proc-melodic-devel")
subdirs("scan_tools-indigo/laser_scan_sparsifier")
subdirs("scan_tools-indigo/laser_scan_splitter")
subdirs("gazebo_ros_pkgs-melodic-devel/gazebo_ros")
subdirs("handle_reflector")
subdirs("scan_tools-indigo/ncd_parser")
subdirs("ira_laser_tools-master")
subdirs("scan_tools-indigo/laser_ortho_projector")
subdirs("scan_tools-indigo/laser_scan_matcher")
subdirs("scan_tools-indigo/polar_scan_matcher")
subdirs("scan_tools-indigo/scan_to_cloud_converter")
subdirs("test_tf")
subdirs("ros_control-melodic-devel/transmission_interface")
subdirs("turtlebot3-melodic-devel/turtlebot3_bringup")
subdirs("turtlebot3-melodic-devel/turtlebot3_example")
subdirs("turtlebot3_simulations-melodic-devel/turtlebot3_fake")
subdirs("turtlebot3_simulations-melodic-devel/turtlebot3_gazebo")
subdirs("turtlebot3-melodic-devel/turtlebot3_slam")
subdirs("turtlebot3-melodic-devel/turtlebot3_teleop")
subdirs("gazebo_ros_pkgs-melodic-devel/gazebo_plugins")
subdirs("ros_control-melodic-devel/joint_limits_interface")
subdirs("gazebo_ros_pkgs-melodic-devel/gazebo_ros_control")
subdirs("urg_node-indigo-devel")
subdirs("nav_car")
subdirs("mrobot_gazebo")
subdirs("turtlebot3-melodic-devel/turtlebot3_description")
