# CMake generated Testfile for 
# Source directory: /home/sjtuwhl/ROBOTLAB_WS/src/urg_node-indigo-devel
# Build directory: /home/sjtuwhl/ROBOTLAB_WS/devel/urg_node-indigo-devel
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(_ctest_urg_node_roslint_package "/home/sjtuwhl/ROBOTLAB_WS/devel/catkin_generated/env_cached.sh" "/usr/bin/python2" "/opt/ros/melodic/share/catkin/cmake/test/run_tests.py" "/home/sjtuwhl/ROBOTLAB_WS/devel/test_results/urg_node/roslint-urg_node.xml" "--working-dir" "/home/sjtuwhl/ROBOTLAB_WS/devel/urg_node-indigo-devel" "--return-code" "/opt/ros/melodic/share/roslint/cmake/../../../lib/roslint/test_wrapper /home/sjtuwhl/ROBOTLAB_WS/devel/test_results/urg_node/roslint-urg_node.xml make roslint_urg_node")
set_tests_properties(_ctest_urg_node_roslint_package PROPERTIES  _BACKTRACE_TRIPLES "/opt/ros/melodic/share/catkin/cmake/test/tests.cmake;143;add_test;/opt/ros/melodic/share/roslint/cmake/roslint-extras.cmake;67;catkin_run_tests_target;/home/sjtuwhl/ROBOTLAB_WS/src/urg_node-indigo-devel/CMakeLists.txt;80;roslint_add_test;/home/sjtuwhl/ROBOTLAB_WS/src/urg_node-indigo-devel/CMakeLists.txt;0;")
add_test(_ctest_urg_node_roslaunch-check_launch_urg_lidar.launch "/home/sjtuwhl/ROBOTLAB_WS/devel/catkin_generated/env_cached.sh" "/usr/bin/python2" "/opt/ros/melodic/share/catkin/cmake/test/run_tests.py" "/home/sjtuwhl/ROBOTLAB_WS/devel/test_results/urg_node/roslaunch-check_launch_urg_lidar.launch.xml" "--return-code" "/home/sjtuwhl/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/192.7142.39/bin/cmake/linux/bin/cmake -E make_directory /home/sjtuwhl/ROBOTLAB_WS/devel/test_results/urg_node" "/opt/ros/melodic/share/roslaunch/cmake/../scripts/roslaunch-check -o '/home/sjtuwhl/ROBOTLAB_WS/devel/test_results/urg_node/roslaunch-check_launch_urg_lidar.launch.xml' '/home/sjtuwhl/ROBOTLAB_WS/src/urg_node-indigo-devel/launch/urg_lidar.launch' ")
set_tests_properties(_ctest_urg_node_roslaunch-check_launch_urg_lidar.launch PROPERTIES  _BACKTRACE_TRIPLES "/opt/ros/melodic/share/catkin/cmake/test/tests.cmake;143;add_test;/opt/ros/melodic/share/roslaunch/cmake/roslaunch-extras.cmake;58;catkin_run_tests_target;/home/sjtuwhl/ROBOTLAB_WS/src/urg_node-indigo-devel/CMakeLists.txt;83;roslaunch_add_file_check;/home/sjtuwhl/ROBOTLAB_WS/src/urg_node-indigo-devel/CMakeLists.txt;0;")
